import {
  AppProvider,
  QueryProvider,
  ThemeProvider,
} from '@/components/providers'
import { Toaster } from '@/components/ui/sonner'
import { TooltipProvider } from '@/components/ui/tooltip'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { Suspense } from 'react'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Speprove',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html suppressHydrationWarning lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='light'
            enableSystem
            disableTransitionOnChange
          >
            <AppProvider>
              {/* <NextTopLoader color='#64b496' showSpinner={false} /> */}
              <TooltipProvider>
                <Suspense>{children}</Suspense>
                <Toaster position='bottom-right' richColors closeButton />
              </TooltipProvider>
            </AppProvider>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  )
}
